aws:
  account_id: '913524902871'
  alias: '913524902871'
  bucket_name: groot-sm-artifacts-913524902871-us-east-1
  region: us-east-1
  role_arn: arn:aws:iam::913524902871:role/GR00TSageMakerRole-913524902871-us-east-1
codebuild:
  training_project: groot-sm-training-build
dataset:
  s3_prefix: datasets/leisaac-pick-orange
  hf_dataset_id: LightwheelAI/leisaac-pick-orange
ecr:
  training_uri: 913524902871.dkr.ecr.us-east-1.amazonaws.com/groot-sm-training:latest
eval:
  instance_type: ml.g5.2xlarge
model:
  hf_model_id: nvidia/GR00T-N1.6-3B
  s3_prefix: models/groot-sm
  groot_version: n1.6
  package_group_name: groot-sm-models
training:
  global_batch_size: 32
  instance_type: ml.g5.12xlarge
  max_steps: 100
  save_steps: 50
  max_wait_seconds: 86400
  use_spot: false
  instance_fallbacks: []
  capacity_timeout_seconds: 900
transform:
  instance_type: ml.m5.2xlarge
mlflow:
  tracking_server_arn: arn:aws:sagemaker:us-east-1:913524902871:mlflow-tracking-server/groot-mlflow-913524902871
  tracking_server_name: groot-mlflow-913524902871
  experiment_name: groot-sm-finetune
