#!/usr/bin/env bash
# Run the Physical AI Dashboard locally (AUTH_MODE=dev → every request is admin, no ALB/Cognito).
#
#   scripts/dev-local.sh                 # aws mode: real data via the deployed ECS web task env
#   scripts/dev-local.sh --offline       # no AWS calls, in-memory store, UI only
#   scripts/dev-local.sh --refresh       # re-fetch the ECS env (cached in .env.aws.local)
#   scripts/dev-local.sh --port 4000 --role researcher --user alice
#
# aws mode reads/writes the *deployed* DynamoDB table with your local AWS credentials.
# The workflow controller and log archiver are forced off so the local process never
# competes with the running ECS controller.
set -euo pipefail

WEB_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="$WEB_DIR/.env.aws.local"   # matches the repo .gitignore pattern .env*.local

MODE=""            # aws | offline (auto-detected when empty)
PORT="${PORT:-3000}"
DEV_ROLE="${DEV_ROLE:-admin}"
DEV_USER="${DEV_USER:-dev}"
REFRESH=0

usage() { sed -n '2,11p' "$0" | sed 's/^# \{0,1\}//'; exit "${1:-0}"; }

while [[ $# -gt 0 ]]; do
  case "$1" in
    --aws) MODE=aws ;;
    --offline) MODE=offline ;;
    --refresh) REFRESH=1 ;;
    --port) PORT="$2"; shift ;;
    --role) DEV_ROLE="$2"; shift ;;
    --user) DEV_USER="$2"; shift ;;
    -h|--help) usage 0 ;;
    *) echo "unknown option: $1" >&2; usage 1 ;;
  esac
  shift
done

log() { printf '\033[1;34m[dev-local]\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33m[dev-local]\033[0m %s\n' "$*" >&2; }
die() { printf '\033[1;31m[dev-local]\033[0m %s\n' "$*" >&2; exit 1; }

# ---- guards -------------------------------------------------------------------
[[ "${NODE_ENV:-}" == "production" ]] && die "NODE_ENV=production is set; dev auth refuses to run. Unset it first."
[[ -n "${AWS_EXECUTION_ENV:-}${ECS_CONTAINER_METADATA_URI_V4:-}" ]] && die "This looks like a deployed container; dev auth is disabled there."
command -v node >/dev/null || die "node not found (>= 20.9 required)"
NODE_MAJOR="$(node -p 'process.versions.node.split(".")[0]')"
(( NODE_MAJOR >= 20 )) || die "node >= 20.9 required, found $(node -v)"

cd "$WEB_DIR"
[[ -d node_modules ]] || { log "node_modules missing → npm ci"; npm ci; }

# ---- mode detection -----------------------------------------------------------
have_aws() {
  command -v aws >/dev/null && command -v jq >/dev/null && aws sts get-caller-identity --query Account --output text 2>/dev/null
}
if [[ -z "$MODE" ]]; then
  if ACCOUNT_ID="$(have_aws)"; then MODE=aws; else MODE=offline; warn "no AWS credentials/aws/jq → falling back to --offline"; fi
fi

# ---- aws mode: pull env from the deployed ECS web task definition ----------------
fetch_ecs_env() {
  local region cluster service td
  region="${AWS_REGION:-${AWS_DEFAULT_REGION:-us-east-1}}"
  ACCOUNT_ID="${ACCOUNT_ID:-$(aws sts get-caller-identity --query Account --output text)}"
  cluster="physical-ai-dashboard-${ACCOUNT_ID}"
  service="$(aws ecs list-services --cluster "$cluster" --region "$region" --query 'serviceArns' --output text 2>/dev/null \
    | tr '\t' '\n' | grep -- '-WebService[A-Z0-9]' | head -1 || true)"
  [[ -n "$service" ]] || die "ECS web service not found in cluster $cluster ($region). Is the dashboard deployed? Use --offline otherwise."
  td="$(aws ecs describe-services --cluster "$cluster" --services "$service" --region "$region" --query 'services[0].taskDefinition' --output text)"
  log "reading env from $td"
  {
    echo "# generated by scripts/dev-local.sh on $(date -u +%FT%TZ) from $td"
    echo "# safe to delete; re-create with --refresh"
    aws ecs describe-task-definition --task-definition "$td" --region "$region" \
      --query 'taskDefinition.containerDefinitions[?name==`web`]|[0].environment' --output json \
      | jq -r '.[] | select(.name != "PORT" and .name != "HOSTNAME") | "\(.name)=\(.value|@sh)"'
  } > "$ENV_FILE"
  chmod 600 "$ENV_FILE"
}

if [[ "$MODE" == aws ]]; then
  if [[ $REFRESH -eq 1 || ! -s "$ENV_FILE" ]]; then fetch_ecs_env; else log "using cached $ENV_FILE (pass --refresh to re-fetch)"; fi
  set -a; # shellcheck disable=SC1090
  source "$ENV_FILE"; set +a
  [[ -n "${TABLE_NAME:-}" ]] || die "TABLE_NAME missing in $ENV_FILE; try --refresh"
else
  # Offline: only the dev flag. config.ts tolerates a bare env and repo.ts picks MemoryKV when TABLE_NAME is unset.
  unset TABLE_NAME
fi

# ---- overrides that must win regardless of mode -----------------------------------
export AUTH_MODE=dev
export DEV_USER DEV_ROLE
export WORKFLOW_CONTROLLER=0        # never run a second controller against the shared table
export LOG_ARCHIVE_ENABLED=0
export DASHBOARD_ORIGIN="http://localhost:${PORT}"

# ---- banner -------------------------------------------------------------------------
echo
log "mode      : $MODE"
log "identity  : $DEV_USER ($DEV_ROLE) — every request is authenticated as this user"
if [[ "$MODE" == aws ]]; then
  log "account   : ${ACCOUNT_ID:-?}  region: ${AWS_REGION:-us-east-1}  table: $TABLE_NAME"
  warn "aws mode uses the DEPLOYED DynamoDB/S3. Creating runs, datasets, or policies here is real."
  warn "controller is OFF locally: submitted workflows are picked up by the ECS controller, not this process."
else
  log "store     : in-memory (lost on exit); AWS-backed pages show 'not configured'"
fi
log "url       : http://localhost:${PORT}   (remote host? ssh -L ${PORT}:localhost:${PORT} <host>)"
echo

exec npm run dev -- --port "$PORT"
