aws:
  account_id: '913524902871'
  bucket_name: hi-groot-n16-bucket
  region: us-west-2
  role_arn: arn:aws:iam::913524902871:role/GR00TSageMakerRole
codebuild:
  inference_project: groot-n16-inference-build
  training_project: groot-n16-training-build
dataset:
  s3_prefix: datasets/my-robot
ecr:
  inference_uri: 913524902871.dkr.ecr.us-west-2.amazonaws.com/groot-n16-inference:latest
  training_uri: 913524902871.dkr.ecr.us-west-2.amazonaws.com/groot-n16-training:latest
inference:
  endpoint_name: groot-n16-endpoint
  instance_type: ml.g5.2xlarge
  model_package_group: groot-n16-models
model:
  hf_model_id: nvidia/GR00T-N1.6-3B
  s3_prefix: models/groot-n16
training:
  global_batch_size: 32
  instance_type: ml.p4d.24xlarge
  max_steps: 10000
  max_wait_seconds: 86400
  num_gpus: 8
  save_steps: 2000
  use_spot: true
